/**
 * THE ROLL-CALL — every tradition the Oracle's globe carries, and the city it
 * is pinned to.
 *
 * This is a STATIC EXCERPT of the live library (`/api/public/library-map`),
 * copied out of the backend so the marketing page can name a hundred and two
 * real traditions without making a request to the API. The app's globe is the
 * live one; if a tradition is added there, this list is merely out of date — it
 * is copy, not data, and nothing breaks.
 *
 * The names are the traditions' own. `Merindinlogun` is not "African
 * astrology", and the point of printing all of them is that none of them is a
 * footnote to another.
 */
export const TRADITIONS = [
  { label: "Akan day names", place: "Kumasi" },
  { label: "Mérìndínlógún", place: "Ile-Ife" },
  { label: "Ngombo, Bamana, bone throwing", place: "Bamako" },
  { label: "Sikidy", place: "Antananarivo" },
  { label: "Andean / Inca wata", place: "Cusco" },
  { label: "Aztec", place: "Tenochtitlan" },
  { label: "Mayan", place: "Tikal" },
  { label: "Native totem", place: "The Plains" },
  { label: "Zapotec / Mixtec count", place: "Monte Albán" },
  { label: "Chiromancy (palmistry)", place: "Athens" },
  { label: "Mian Xiang (face reading)", place: "Xi'an" },
  { label: "Moleosophy", place: "London" },
  { label: "Physiognomy (European)", place: "Athens" },
  { label: "Shou Xiang", place: "Xi'an" },
  { label: "Svara Śāstra", place: "Varanasi" },
  { label: "Sāmudrika Śāstra", place: "Varanasi" },
  { label: "Ba Zhai (Eight Mansions)", place: "Xi'an" },
  { label: "Cheng Gu (bone weight)", place: "Xi'an" },
  { label: "Chinese (BaZi)", place: "Xi'an" },
  { label: "Da Liu Ren (this moment)", place: "Luoyang" },
  { label: "Flying Star feng shui", place: "Guangzhou" },
  { label: "Guo Lao Xing Zong", place: "Xi'an" },
  { label: "Kau Chim (temple lots)", place: "Quanzhou" },
  { label: "Ling Qi Jing", place: "Nanjing" },
  { label: "Lo Shu grid", place: "Luoyang" },
  { label: "Plum Blossom (this moment)", place: "Luoyang" },
  { label: "Qi Men Dun Jia (this moment)", place: "Luoyang" },
  { label: "San He feng shui", place: "Ganzhou" },
  { label: "Tai Yi Shen Shu (era)", place: "Luoyang" },
  { label: "Taoist phase", place: "Mount Qingcheng" },
  { label: "Tie Ban Shen Shu", place: "Luoyang" },
  { label: "Xiao Liu Ren", place: "Central China" },
  { label: "Gunghap (Korean compatibility)", place: "Seoul" },
  { label: "Nine Star Ki", place: "Tokyo" },
  { label: "Omikuji", place: "Kyoto" },
  { label: "Onmyōdō (Japanese almanac)", place: "Kyoto" },
  { label: "Saju Palja (Korean)", place: "Seoul" },
  { label: "Sanmei-gaku", place: "Tokyo" },
  { label: "Seimei Handan", place: "Tokyo" },
  { label: "Shichū Suimei (Japanese)", place: "Kyoto" },
  { label: "Tojeong Bigyeol (Korean almanac)", place: "Boryeong" },
  { label: "Tứ Trụ (Vietnamese)", place: "Hanoi" },
  { label: "Tử Vi Đẩu Số (Vietnamese)", place: "Hanoi" },
  { label: "Anglo-Saxon Futhorc", place: "York" },
  { label: "Baltic and Finnic folk", place: "The Baltic" },
  { label: "Bibliomancy", place: "Rome" },
  { label: "Celtic tree", place: "Tara" },
  { label: "Cleromancy (lots)", place: "Babylon" },
  { label: "Dowsing / pendulum", place: "The Harz" },
  { label: "Goralot", place: "Kraków" },
  { label: "Kipper cards", place: "Munich" },
  { label: "Playing-card cartomancy", place: "Paris" },
  { label: "Scrying", place: "Memphis" },
  { label: "Sibilla deck", place: "Milan" },
  { label: "Slavic folk divination", place: "Kyiv" },
  { label: "Tasseography", place: "London" },
  { label: "Younger Futhark", place: "Uppsala" },
  { label: "Mongolian Zurhai", place: "Ulaanbaatar" },
  { label: "Tibetan", place: "Lhasa" },
  { label: "Tibetan Kar-tsi", place: "Lhasa" },
  { label: "Angel numbers", place: "Sedona" },
  { label: "Gematria (all methods)", place: "Jerusalem" },
  { label: "Isopsephy (Greek)", place: "Athens" },
  { label: "Kabbalah", place: "Safed" },
  { label: "Mazalot", place: "Jerusalem" },
  { label: "Aboriginal Australian sky knowledge", place: "Central Australia" },
  { label: "Khmer Horasastra", place: "Angkor" },
  { label: "Lao calendar", place: "Luang Prabang" },
  { label: "Mahabote", place: "Bagan" },
  { label: "Pawukon (Bali)", place: "Bali" },
  { label: "Polynesian moon nights", place: "Aotearoa" },
  { label: "Tahitian moon nights", place: "Tahiti" },
  { label: "Thai Horasat", place: "Ayutthaya" },
  { label: "Weton (Java)", place: "Yogyakarta" },
  { label: "Abjad (Arabic)", place: "Kufa" },
  { label: "Firdaria (Persian time-lords)", place: "Isfahan" },
  { label: "Fāl-e Ḥāfeẓ", place: "Shiraz" },
  { label: "Ikhtiyārāt", place: "Baghdad" },
  { label: "Istikhāra", place: "Medina" },
  { label: "Jafr", place: "Medina" },
  { label: "Lunar mansions (manazil)", place: "Hejaz" },
  { label: "Zāʾirja", place: "Fez" },
  { label: "Alchemy", place: "Alexandria" },
  { label: "Astrocartography", place: "San Francisco" },
  { label: "Barbault cyclic index (world)", place: "Paris" },
  { label: "Bradley siderograph (markets)", place: "Los Angeles" },
  { label: "Egyptian decan", place: "Thebes" },
  { label: "Evolutionary astrology", place: "Boulder" },
  { label: "Hermetic law", place: "Alexandria" },
  { label: "Human Design", place: "Ibiza" },
  { label: "Sacred geometry", place: "Athens" },
  { label: "Solar barycentric (Landscheidt)", place: "Hamburg" },
  { label: "Traditional medical astrology", place: "Kos" },
  { label: "Western", place: "Alexandria" },
  { label: "Aṣṭamaṅgala Praśna", place: "Thrissur" },
  { label: "KP (Krishnamurti)", place: "Chennai" },
  { label: "Numerology", place: "Varanasi" },
  { label: "Ramala", place: "Delhi" },
  { label: "Sarvatobhadra Chakra", place: "Awadh" },
  { label: "Sinhala Nekath", place: "Kandy" },
  { label: "Tamil numerology", place: "Madurai" },
  { label: "Vedic (BPHS)", place: "Varanasi" },
];

export default TRADITIONS;
