import { chromium } from 'playwright';
import fs from 'fs';
const S = process.env.WORK || '/tmp/app-screens';
const VID = `${S}/vidorb`; fs.rmSync(VID, { recursive: true, force: true }); fs.mkdirSync(VID);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'] });
const ctx = await b.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto('http://localhost:3223/#orb', { waitUntil: 'load' });
await p.waitForFunction(() => window.__ready, null, { timeout: 30000 });
await p.waitForTimeout(1500);
const cdp = await ctx.newCDPSession(p);
const frames = [];
cdp.on('Page.screencastFrame', async (f) => { frames.push({ t: f.metadata.timestamp, data: f.data }); try { await cdp.send('Page.screencastFrameAck', { sessionId: f.sessionId }); } catch (_) {} });
await cdp.send('Page.startScreencast', { format: 'jpeg', quality: 92, maxWidth: 786, maxHeight: 1704 });
await p.waitForTimeout(10000);
await cdp.send('Page.stopScreencast');
let list = '';
frames.forEach((f, i) => { const n = `f${String(i).padStart(5, '0')}.jpg`; fs.writeFileSync(`${VID}/${n}`, Buffer.from(f.data, 'base64')); list += `file '${n}'\nduration ${(i + 1 < frames.length ? frames[i + 1].t - f.t : 0.05).toFixed(4)}\n`; });
list += `file 'f${String(frames.length - 1).padStart(5, '0')}.jpg'\n`;
fs.writeFileSync(`${VID}/list.txt`, list);
console.log('frames', frames.length);
await b.close();
