/**
 * /editorial-standards — how the site's pages are written, what they rest on,
 * and how to report a mistake. Search engines and answer engines weigh a
 * source by whether it says who stands behind it and how it checks itself;
 * this page is that statement, linked from every page's footer and named as
 * the organization's publishingPrinciples in the JSON-LD.
 */
import Link from 'next/link';
import { pageMeta, breadcrumbLd, JsonLd, abs, SITE } from '../../lib/seo';
import { UPDATED } from '../../lib/guides';
import { Doc, LINK } from '../../components/site/Doc';

const PATH = '/editorial-standards';
const TITLE = 'Editorial Standards and Sources';
const DESC = 'How Plutto’s guides, reference pages and calculators are written and checked: the ephemeris, the classical sources, how AI is used, and how to report a correction.';

export const metadata = pageMeta({ title: TITLE, description: DESC, path: PATH });

const SOURCES = [
  ['Astronomy', 'Swiss Ephemeris (Astrodienst), for every planetary position, house cusp and ayanamsa. Vedic charts use the Lahiri ayanamsa; KP the Krishnamurti ayanamsa with Placidus cusps; Western charts the tropical zodiac with Placidus houses.'],
  ['Vedic astrology (Jyotish)', 'Brihat Parashara Hora Shastra for the grahas, nakshatras, the Vimshottari dasha and the vargas; Phaladeepika and Saravali for yogas and interpretation.'],
  ['KP astrology', 'K. S. Krishnamurti’s KP Readers, for the sub-lord theory, the 249 divisions and horary by number.'],
  ['Western astrology', 'Ptolemy’s Tetrabiblos for the signs, rulerships and dignities, read beside the modern psychological tradition.'],
  ['Chinese astrology (BaZi)', 'The Zi Ping method (Yuan Hai Zi Ping) for the Four Pillars, with the solar-term calendar, so the year turns at Li Chun rather than on 1 January.'],
  ['Numerology', 'Pythagorean letter values for the life path and name numbers; Cheiro’s Chaldean table for Chaldean name numbers; Ank Jyotish for the Indian moolank and bhagyank.'],
  ['The calculators', 'The Moon sign and Chinese zodiac calculators compute in your browser with astronomy-engine (MIT licence), using the Lahiri ayanamsa and ΔT of Swiss Ephemeris itself; tested against Swiss Ephemeris on 5,000 random moments from 1900 to 2100, the Moon agreed within 4.2 arcseconds. Birth times are converted with the IANA time-zone history your browser ships. The sign-ingress and Li Chun times on the reference pages are computed the same way.'],
];

export default function Page() {
  const page = {
    '@context': 'https://schema.org', '@type': 'WebPage', name: TITLE, url: abs(PATH), description: DESC,
    dateModified: UPDATED, publisher: { '@id': `${SITE.url}/#organization` }, inLanguage: 'en',
  };
  return (
    <>
      <JsonLd data={page} />
      <JsonLd data={breadcrumbLd([{ name: 'Editorial standards', path: PATH }])} />
      <Doc eyebrow="How we write" title="Editorial standards and sources" crumbs={[{ name: 'Editorial standards', path: PATH }]}>
        <p className="speakable !mt-0 max-w-2xl text-[19px] leading-[1.65] text-white/85">
          Every guide, reference page and calculator on plutto.space is written and edited by the Plutto team at {SITE.companyShort}, with AI assistance, and checked against the classical source of the tradition it describes. The astronomy is computed, never estimated; the interpretations are the traditions’ own; and nothing here is presented as science or as advice.
        </p>

        <h2>What we stand behind</h2>
        <p>The positions are exact: they come from Swiss Ephemeris, the same astronomical library professional astrology software is built on. The calculators show their working, so any result can be checked by hand.</p>
        <p>The meanings are the traditions’ own, stated as what the tradition holds — “Vedic astrology reads the Moon’s nakshatra as…”, not “you are…”. Where traditions disagree, we say so and name both.</p>

        <h2>What we do not claim</h2>
        <p>Astrology is not a science, and Plutto does not claim to predict the future. No page gives medical, legal or financial advice. We publish no ratings, review counts or user numbers until there are real ones to publish.</p>

        <h2>How AI is used</h2>
        <p>Readings inside the app are generated by AI language models from your computed chart: the positions are calculated first, and the model interprets them within the tradition you choose. The spoken voice is AI as well. The pages on this site are drafted with AI assistance, then edited and checked against the sources below.</p>

        <h2>Sources</h2>
        <dl className="mt-6 max-w-2xl divide-y divide-white/[0.07] border-y border-white/[0.07]">
          {SOURCES.map(([k, v]) => (
            <div key={k} className="py-4">
              <dt className="font-semibold text-white">{k}</dt>
              <dd className="mt-1">{v}</dd>
            </div>
          ))}
        </dl>

        <h2>Corrections</h2>
        <p>
          Found a mistake — a wrong degree, a misattributed meaning, a calculation that disagrees with yours? Write to{' '}
          <a href={`mailto:${SITE.email}?subject=Correction`} className={LINK}>{SITE.email}</a> with the page and what you found. We fix factual errors and update the page’s date.
        </p>
        <p>Last reviewed {new Date(UPDATED).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}.</p>

        <p className="!mt-12">
          <Link href="/guides" className={LINK}>Guides</Link> · <Link href="/tools" className={LINK}>Calculators</Link> · <Link href="/faq" className={LINK}>FAQ</Link> · <Link href="/about" className={LINK}>How it works</Link>
        </p>
      </Doc>
    </>
  );
}
